/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TableTableNumberRouteImport } from './routes/table.$tableNumber'
import { Route as StaffLoginRouteImport } from './routes/staff.login'

const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableTableNumberRoute = TableTableNumberRouteImport.update({
  id: '/table/$tableNumber',
  path: '/table/$tableNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kitchen': typeof KitchenRoute
  '/staff/login': typeof StaffLoginRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kitchen': typeof KitchenRoute
  '/staff/login': typeof StaffLoginRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kitchen': typeof KitchenRoute
  '/staff/login': typeof StaffLoginRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kitchen'
    | '/staff/login'
    | '/table/$tableNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/kitchen' | '/staff/login' | '/table/$tableNumber'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kitchen'
    | '/staff/login'
    | '/table/$tableNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  KitchenRoute: typeof KitchenRoute
  StaffLoginRoute: typeof StaffLoginRoute
  TableTableNumberRoute: typeof TableTableNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$tableNumber': {
      id: '/table/$tableNumber'
      path: '/table/$tableNumber'
      fullPath: '/table/$tableNumber'
      preLoaderRoute: typeof TableTableNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  KitchenRoute: KitchenRoute,
  StaffLoginRoute: StaffLoginRoute,
  TableTableNumberRoute: TableTableNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
